package systemdns

import (
	"reflect"
	"testing"
)

func TestParseResolvConf(t *testing.T) {
	content := `# Generated by NetworkManager
search example.com corp.local
nameserver 192.168.1.1
nameserver 8.8.8.8
nameserver 192.168.1.1
options timeout:2 attempts:3
`

	searchDomains, nameservers, options := parseResolvConf(content)

	if !reflect.DeepEqual(searchDomains, []string{"example.com", "corp.local"}) {
		t.Errorf("Expected search domains [example.com corp.local], got %v", searchDomains)
	}

	// 重复的 nameserver 应去重且保持顺序
	if !reflect.DeepEqual(nameservers, []string{"192.168.1.1", "8.8.8.8"}) {
		t.Errorf("Expected nameservers [192.168.1.1 8.8.8.8], got %v", nameservers)
	}

	if !reflect.DeepEqual(options, []string{"timeout:2", "attempts:3"}) {
		t.Errorf("Expected options [timeout:2 attempts:3], got %v", options)
	}
}

func TestParseResolvConfEmpty(t *testing.T) {
	content := "# only comments\n; another comment\n\n"
	searchDomains, nameservers, options := parseResolvConf(content)

	if len(searchDomains) != 0 || len(nameservers) != 0 || len(options) != 0 {
		t.Errorf("Expected empty result, got search=%v ns=%v options=%v", searchDomains, nameservers, options)
	}
}

func TestParseResolvConfDomainFallback(t *testing.T) {
	content := "domain example.com\nnameserver 10.0.0.1\n"

	searchDomains, _, _ := parseResolvConf(content)
	if !reflect.DeepEqual(searchDomains, []string{"example.com"}) {
		t.Errorf("Expected search domains [example.com], got %v", searchDomains)
	}
}

func TestParseResolvConfSearchPriority(t *testing.T) {
	// search 与 domain 同时存在时 search 优先
	content := "search a.com\nnameserver 10.0.0.1\ndomain b.com\n"

	searchDomains, _, _ := parseResolvConf(content)
	if !reflect.DeepEqual(searchDomains, []string{"a.com"}) {
		t.Errorf("Expected search domains [a.com] (search takes priority), got %v", searchDomains)
	}
}
