//go:build darwin

package systemdns

import (
	"context"
	"os"
	"os/exec"
	"strings"
	"time"

	pkgerrors "github.com/kkkqkx123/mihomo-cli/pkg/errors"
)

const (
	// ScutilDNS 输出来源描述
	ScutilDNS = "scutil --dns"
	// ScutilTimeout scutil 命令执行超时
	ScutilTimeout = 5 * time.Second
)

// darwinSystemDNS macOS system DNS provider
type darwinSystemDNS struct{}

// newPlatformSystemDNS creates a new macOS system DNS provider
func newPlatformSystemDNS() SystemDNS {
	return &darwinSystemDNS{}
}

// GetConfig queries system DNS via scutil --dns,
// falls back to /etc/resolv.conf when the command is unavailable.
func (sd *darwinSystemDNS) GetConfig() (*SystemDNSConfig, error) {
	if config, err := queryScutilDNS(); err == nil {
		return config, nil
	}

	// Fallback: /etc/resolv.conf (generated by macOS from active resolvers)
	data, err := os.ReadFile(ResolvConf)
	if err != nil {
		return nil, pkgerrors.ErrService("failed to query system DNS (scutil and resolv.conf both unavailable)", err)
	}

	searchDomains, nameservers, options := parseResolvConf(string(data))

	return &SystemDNSConfig{
		SearchDomains: searchDomains,
		Nameservers:   nameservers,
		Options:       options,
		Source:        ResolvConf,
	}, nil
}

// queryScutilDNS runs `scutil --dns` and parses resolver blocks.
func queryScutilDNS() (*SystemDNSConfig, error) {
	ctx, cancel := context.WithTimeout(context.Background(), ScutilTimeout)
	defer cancel()

	output, err := exec.CommandContext(ctx, "scutil", "--dns").Output()
	if err != nil {
		return nil, err
	}

	config, err := parseScutilDNSOutput(string(output))
	if err != nil {
		return nil, err
	}
	config.Source = ScutilDNS
	return config, nil
}

// parseScutilDNSOutput 解析 `scutil --dns` 输出。
// Format example:
//
//	resolver #1
//	  search domain[0] : example.com
//	  nameserver[0] : 8.8.8.8
//	  nameserver[1] : 8.8.4.4
func parseScutilDNSOutput(output string) (*SystemDNSConfig, error) {
	config := &SystemDNSConfig{}
	seenNS := make(map[string]bool)

	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}

		switch fields[0] {
		case "nameserver":
			// nameserver[0] : 8.8.8.8
			ns := fields[len(fields)-1]
			if !seenNS[ns] {
				seenNS[ns] = true
				config.Nameservers = append(config.Nameservers, ns)
			}
		case "search":
			// search domain[0] : example.com
			if fields[1] == "domain" {
				config.SearchDomains = append(config.SearchDomains, fields[len(fields)-1])
			}
		}
	}

	if len(config.Nameservers) == 0 {
		return nil, pkgerrors.ErrService("no nameserver found in scutil --dns output", nil)
	}

	return config, nil
}

// IsSupported returns true on macOS
func (sd *darwinSystemDNS) IsSupported() bool {
	return true
}
